#!/bin/bash

set -euo pipefail

args="$0 $@"

while ! echo $1 | grep '.rpm$' &> /dev/null; do
  shift
done

# Package is either $1 or it will be empty and error
package=$1

if [ -z "$package" ]; then
  echo
  echo "ERROR: Couldn't determine which param was the rpm"
  echo "  fake dnf called with [$args]"
  echo
  exit 10
fi

rpm-ostree install "${package}"
