FROM fedora:38

LABEL com.github.containers.toolbox=true

## Install deps
RUN dnf install -y which git autoconf automake libtool gcc-c++ libusb1-devel libzip-devel psmisc fuse-devel \
                   openssl-devel readline-devel libcurl-devel zlib-devel libxml2-devel && \
    dnf clean all

# Script to build libimobiledevice
ADD files/limd-build-linux.sh /usr/local/bin

# libimobiledevice build
RUN mkdir /tmp/workdir && \
    cd /tmp/workdir && \
    RUN_AS_ROOT=1 /usr/local/bin/limd-build-linux.sh
