FROM quay.io/almalinuxorg/almalinux-bootc:10

# Update the system (must be run first!)
RUN dnf update -y && \
    dnf clean all

# This is needed to use dnf config-manager and dnf versionlock
RUN dnf install -y dnf-plugins-core dnf-plugin-versionlock && \
    dnf clean all

# Ensure that the kernel is never updated again (more compatible with zfs)
RUN dnf versionlock add kernel* && \
    dnf clean all

# Install zfs release package
# From: https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/index.html
RUN dnf install -y https://zfsonlinux.org/epel/zfs-release-2-8$(rpm --eval "%{dist}").noarch.rpm && \
    dnf clean all

# Use the static zfs kmod istead of dkms
# From: https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/index.html#kabi-tracking-kmod
RUN dnf config-manager --disable zfs && \
    dnf config-manager --enable zfs-kmod && \
    dnf install -y zfs && \
    dnf clean all

# Install epel
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm && \
    dnf clean all

# Cleanup image for linting
RUN rm -rf /var && mkdir /var && \
    rm -rf /boot && mkdir /boot

# Verify image is good (must be run last!)
RUN bootc container lint --fatal-warnings
