FROM ghcr.io/twiest/silverblue-base:latest

# Install UPS software
RUN dnf install -y nut baobab && \
    dnf clean all

# Cleanup image for linting
RUN rm -rf /var && mkdir /var && \
    rm -rf /boot && mkdir /boot

# Verify image is good
RUN bootc container lint --fatal-warnings --skip baseimage-composefs
