FROM ghcr.io/cgwalters/fedora-silverblue:37

# Install rpmfusion repos
RUN rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm && \
    rpm-ostree install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

# Install ZFS repository
RUN rpm-ostree install https://zfsonlinux.org/fedora/zfs-release-2-2$(rpm --eval "%{dist}").noarch.rpm && \
    # cleanup and verification stage
    rm -vrf /var /*.rpm && \
    ostree container commit

# Install the basics
RUN rpm-ostree install \
    distrobox iotop screen snapper strace terminator thunderbird vim gnome-tweak-tool neofetch \
    cheese vlc seahorse kernel-devel && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

# Install zfs
RUN rpm-ostree install zfs && \
    # TODO: Remove the following line once this bug is fixed: https://github.com/coreos/rpm-ostree/issues/4201
    test -f /usr/bin/ld || ln -s /usr/bin/ld.bfd /usr/bin/ld && \
    dkms autoinstall -k $(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}') && \
    # cleanup and verification stage
    test -h /usr/bin/ld && rm -v /usr/bin/ld && \
    rm -vrf /var && \
    ostree container commit

RUN echo "Defaults timestamp_timeout=1200" > /etc/sudoers.d/timeout && \
    chmod 660 /etc/sudoers.d/timeout
