FROM ghcr.io/twiest/silverblue-zfs-base:latest

# Install rpmfusion repos
RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm && \
    dnf install -y https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    # cleanup and verification stage
    dnf clean all

# Install virtualization
RUN dnf install -y @virtualization libvirt-daemon libvirt-daemon-driver-storage-disk && \
    dnf clean all

# Install the basics
# TODO: evaluate restic as a multi-threaded possible replacement for borg once restic reaches 1.0 status
#       https://github.com/restic/restic
RUN dnf install -y \
    distrobox iotop screen snapper strace terminator thunderbird vim gnome-tweak-tool fastfetch fuse-encfs borgbackup \
    keepassxc seahorse htop rclone inxi fio cracklib-dicts hwinfo gst ipmitool pv fuse-sshfs nvme-cli nc firewall-config \
    etckeeper sg3_utils lshw podman-docker docker-compose smartmontools gsmartcontrol hdparm zstd pbzip2 lz4 \
    udisks2-btrfs udisks2-lvm2 udisks2-iscsi easyeffects android-tools wireguard-tools iperf3 ansible meld \
    gdouros-symbola-fonts gdisk xonsh libreoffice-calc libreoffice chromium nvtop gocryptfs && \
    ln -vsf /usr/bin/ncat /usr/bin/nc && \
    dnf clean all

# Install tailscale
RUN cd /etc/yum.repos.d/ && curl -LO https://pkgs.tailscale.com/stable/fedora/tailscale.repo && \
    dnf install -y tailscale && \
    dnf clean all && \
    rm /etc/yum.repos.d/tailscale.repo # Removing makes dnf queries faster

# Add tcpping for convenience
ADD files/cli/tcpping /usr/bin/tcpping

RUN echo "Defaults timestamp_timeout=1200" > /etc/sudoers.d/timeout && \
    chmod 660 /etc/sudoers.d/timeout

# Add config.d
ADD files/config.d/config.d.timer /etc/systemd/system
ADD files/config.d/config.d.service /etc/systemd/system
ADD files/config.d/config.d.sh /usr/bin
RUN systemctl enable config.d.timer

# Add polkit files
ADD files/polkitd/50-twiest-rpm-ostree-allow-update-from-all-users.rules /usr/share/polkit-1/rules.d

# Make sure fstrim works on luks devices including root
ADD files/config.d/00-add-luks-fstrim-kargs.sh /etc/config.d/00-add-luks-fstrim-kargs.sh

# Set vim as default editor
RUN rm /etc/profile.d/nano-default-editor.sh
ADD files/profile.d/vim-default-editor.sh /etc/profile.d/vim-default-editor.sh

# Enable git prompt
ADD files/profile.d/git-prompt.sh /etc/profile.d/git-prompt.sh

# Add build date
ADD files/add-build-date.sh /bin
RUN /bin/add-build-date.sh

# Cleanup image for linting
RUN test -f /usr/lib/sysusers.d/libvirt.conf || echo -e 'g libvirt 963' > /usr/lib/sysusers.d/libvirt.conf && \
    test -f /usr/lib/sysusers.d/screen.conf || echo -e 'g screen 84' > /usr/lib/sysusers.d/screen.conf

RUN dnf remove -y glusterfs && \
    sed -i '/gluster/d' /etc/passwd && \
    sed -i '/gluster/d' /etc/group && \
    rm -vrf /run/dnf && \
    rm -vrf /run/screen && \
    rm -vrf /run/selinux-policy && \
    rm -vrf /tmp && mkdir /tmp && \
    rm -vrf /var && mkdir /var && \
    rm -vrf /boot && mkdir /boot

# Verify image is good
RUN bootc container lint --fatal-warnings --skip baseimage-composefs
