FROM ghcr.io/twiest/silverblue-base:latest

# Install UPS software
RUN rpm-ostree install nut && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

# k3s install script
ADD files/k3s-install.sh /usr/bin/k3s-install.sh

# Run the install script. Not much should need to be done.
RUN INSTALL_K3S_SKIP_START=true \
    INSTALL_K3S_VERSION=v1.27.4+k3s1 \
    INSTALL_K3S_SKIP_ENABLE=true \
    INSTALL_K3S_BIN_DIR=/usr/bin \
    bash -x /usr/bin/k3s-install.sh && \
    ln -s /usr/bin/kubectl /usr/bin/k

# Get rid of both install and uninstall. Handled by image build. Do final seal.
RUN rm /usr/bin/k3s-uninstall.sh /usr/bin/k3s-install.sh && \
    ostree container commit
