FROM ghcr.io/twiest/silverblue-builder-libimobiledevice:latest as builder

FROM ghcr.io/twiest/silverblue-base:latest
COPY --from=builder /usr/local /usr
COPY --from=builder /usr/local/lib /usr/lib64
