FROM ghcr.io/cgwalters/fedora-silverblue:38

# Install ZFS repository
RUN rpm-ostree install https://zfsonlinux.org/fedora/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm && \
    # cleanup and verification stage
    rm -vrf /var /*.rpm && \
    ostree container commit

# Install dkms deps
RUN rpm-ostree install \
    kernel-devel kernel-devel-matched kernel-headers kernel-srpm-macros && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

# TODO: Remove the following line once these bugs are fixed:
# - https://github.com/coreos/rpm-ostree/issues/4201
# - https://github.com/coreos/rpm-ostree/issues/1614
RUN test -f /usr/bin/ld || ln -s /usr/bin/ld.bfd /usr/bin/ld

# Install zfs and tell dkms to install the module
RUN rpm-ostree install zfs zfs-dracut && \
    dkms autoinstall -k $(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}') && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

# Add samsung usb udev rules so that dracut picks them up (makes trim work)
COPY files/dracut/10samsung-usb-udev /usr/lib/dracut/modules.d/10samsung-usb-udev/

# Add samsung usb udev rules for post boot trim to work
ADD  files/dracut/10samsung-usb-udev/10-samsung-usb.rules /etc/udev/rules.d/10-samsung-usb.rules

# Fix selinux so that it allows zfs to mount snapshots
ADD files/selinux/twiest-zfs.pp /usr/share/selinux/packages/
ADD files/selinux/twiest-zfs.pp.bz2 /usr/share/selinux/packages/
ADD files/selinux/twiest-zfs-selinux.service /etc/systemd/system/
RUN systemctl enable twiest-zfs-selinux

# Install dracut requirements
RUN rpm-ostree install lsscsi busybox rng-tools dmraid nvme-cli biosdevname device-mapper-multipath && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

# Setup zfs for inclusion in dracut
RUN echo 'add_dracutmodules+=" zfs "' > /etc/dracut.conf.d/zfs.conf && \
    echo 'force_drivers+=" zfs "' >> /etc/dracut.conf.d/zfs.conf

# Run dracut to build a new initrd
RUN export KERNEL_VERSION="$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
    stock_arguments=$(lsinitrd "/lib/modules/${KERNEL_VERSION}/initramfs.img"  | grep '^Arguments: ' | sed 's/^Arguments: //') && \
    mkdir -p /tmp/dracut /var/roothome && \
    bash <(/usr/bin/echo "dracut $stock_arguments") && \
    rm -rf /var/* /tmp/*  && \
    ostree container commit

# Move the new initrd into place while keeping the stock initrd in the image for reference.
RUN export KERNEL_VERSION="$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
    mv -v "/lib/modules/${KERNEL_VERSION}/initramfs.img" "/lib/modules/${KERNEL_VERSION}/initramfs.stock.img" && \
    mv -v /boot/initramfs*.img "/lib/modules/${KERNEL_VERSION}/initramfs.img" && \
    ostree container commit

# Show that the initrd includes the samsung udev rules service:
RUN lsinitrd /lib/modules/*/initramfs.img | grep 10-samsung-usb.rules

# TODO: Remove the following line once these bugs are fixed:
# - https://github.com/coreos/rpm-ostree/issues/4201
# - https://github.com/coreos/rpm-ostree/issues/1614
RUN test -h /usr/bin/ld && rm -v /usr/bin/ld
