FROM fedora:41 AS downloader

RUN dnf install -y dnf-plugins-core wget && \
    dnf clean all

COPY files/download-kernels.sh /tmp
RUN /tmp/download-kernels.sh

FROM scratch
COPY --from=downloader /tmp/rpms /rpms
