FROM ghcr.io/twiest/silverblue-shared-builder-brave:latest as builder-brave

FROM ghcr.io/twiest/silverblue-shared-builder-python-validity:latest as builder-python-validity

FROM ghcr.io/twiest/silverblue-base:latest

# Add brave repo
RUN dnf config-manager addrepo --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo && \
    rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc && \
    dnf clean all

## Remove incompatible fingerprint utils
RUN dnf remove -y fprintd-pam fprintd && \
    dnf clean all

# Install fingerprint utils
COPY --from=builder-python-validity /rpms /tmp/python-validity-rpms
RUN dnf install -y /tmp/python-validity-rpms/fprintd-clients-*.rpm \
                       /tmp/python-validity-rpms/fprintd-clients-pam-*.rpm \
                       /tmp/python-validity-rpms/open-fprintd-*.rpm \
                       /tmp/python-validity-rpms/python3-validity-*.rpm && \
    systemctl enable python3-validity && \
    dnf clean all

# python-validity still wants to write to usr. This sets up symlinks so that it goes to /var instead.
RUN mv /usr/share/python-validity/playground /usr/share/python-validity-playground && \
    rm -vrf /usr/share/python-validity && \
    ln -s /var/lib/python-validity /usr/share/python-validity && \
    sed -i 's#^ExecStart=/usr/lib/python-validity/dbus-service --debug$#ExecStart=/usr/lib/python-validity/dbus-service#' /usr/lib/systemd/system/python3-validity.service && \
    echo 'd /var/lib/python-validity 0755 root root -' > /usr/lib/tmpfiles.d/python-validity.conf && \
    echo 'f /var/lib/python-validity/backoff 0644 root root -' >> /usr/lib/tmpfiles.d/python-validity.conf && \
    echo 'f /var/lib/python-validity/calib-data.bin 0644 root root -' >> /usr/lib/tmpfiles.d/python-validity.conf && \
    echo 'L /var/lib/python-validity/playground - - - - /usr/share/python-validity-playground' >> /usr/lib/tmpfiles.d/python-validity.conf

# Install rebuilt / silverblue compatible brave-keyring
COPY --from=builder-brave /rpms /tmp/brave-rpms
RUN dnf install -y /tmp/brave-rpms/brave-keyring-*.rpm && \
    dnf clean all

# Install non-distro apps
RUN mkdir -p /var/opt && \
    dnf install -y brave-browser && \
    mv /var/opt/brave.com /usr/lib/brave.com && \
    echo 'L /opt/brave.com - - - - ../../usr/lib/brave.com' > /usr/lib/tmpfiles.d/brave.com.conf && \
    dnf clean all

# Cleanup image for linting
RUN rm -rf /var && mkdir /var && \
    rm -rf /boot && mkdir /boot

# Verify image is good
RUN bootc container lint --fatal-warnings --skip baseimage-composefs
