FROM fedora:38 as builder

# Setup dnf
RUN dnf install -y dnf-plugins-core && \
    dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo && \
    rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc && \
    dnf clean metadata

# Download the brave-keyring rpm
RUN cd /root && \
    dnf download brave-browser brave-keyring liberation-fonts && \
    dnf -y install rpmrebuild && \
    dnf clean metadata

# Rebuild the brave-keyring rpm (needs to be rebuilt without %post to make it compatible with silverblue)
RUN cd /root && \
    rpmrebuild --package --change-files='echo > "$RPMREBUILD_TMPDIR/work/post.1"' -d ./new_pkg/ brave-keyring*.rpm && \
    ls -la --color /root/new_pkg/noarch



FROM ghcr.io/twiest/silverblue-base:latest

ADD copr-tigro-python-validity.repo /etc/yum.repos.d/

# Add base distro tools
RUN rpm-ostree install libimobiledevice-utils ifuse && \
    rm -vrf /var && \
    ostree container commit

# Add brave repo
RUN dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/ && \
    rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc && \
    dnf clean all

## Remove incompatible fingerprint utils
RUN rpm-ostree uninstall fprintd-pam fprintd && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

# Install fingerprint utils
RUN rpm-ostree install fprintd-clients fprintd-clients-pam open-fprintd python3-validity && \
    systemctl enable python3-validity && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

# python-validity still wants to write to usr. This sets up symlinks so that it goes to /var instead.
RUN mv /usr/share/python-validity/playground /usr/share/python-validity-playground && \
    rm -vrf /usr/share/python-validity && \
    ln -s /var/lib/python-validity /usr/share/python-validity && \
    sed -i 's#^ExecStart=/usr/lib/python-validity/dbus-service --debug$#ExecStart=/usr/lib/python-validity/dbus-service#' /usr/lib/systemd/system/python3-validity.service && \
    echo 'd /var/lib/python-validity 0755 root root -' > /usr/lib/tmpfiles.d/python-validity.conf && \
    echo 'f /var/lib/python-validity/backoff 0644 root root -' >> /usr/lib/tmpfiles.d/python-validity.conf && \
    echo 'f /var/lib/python-validity/calib-data.bin 0644 root root -' >> /usr/lib/tmpfiles.d/python-validity.conf && \
    echo 'L /var/lib/python-validity/playground - - - - /usr/share/python-validity-playground' >> /usr/lib/tmpfiles.d/python-validity.conf

# Install rebuilt / silverblue compatible brave-keyring
COPY --from=builder /root/new_pkg/noarch/brave-keyring*.rpm /tmp
RUN rpm-ostree install /tmp/brave-keyring*.rpm && \
    rm /tmp/brave-keyring*.rpm && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit

## Add fingerprint files
#ADD python-validity/6_07f_lenovo_mis_qm.xpfwext /usr/share/python-validity/
#ADD python-validity/backoff /usr/share/python-validity/
#ADD python-validity/calib-data.bin /usr/share/python-validity/

# Install non-distro apps
RUN mkdir -p /var/opt && \
    rpm-ostree install brave-browser && \
    mv /var/opt/brave.com /usr/lib/brave.com && \
    echo 'L /opt/brave.com - - - - ../../usr/lib/brave.com' > /usr/lib/tmpfiles.d/brave.com.conf && \
    # cleanup and verification stage
    rm -vrf /var && \
    ostree container commit
