
name: Build
on:
  schedule:
    - cron: "00 10 * * *"
  push:
    branches: ["main"]
  workflow_dispatch: # This line enables manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  silverblue-shared-downloader-kernel-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-shared-downloader-kernel-cache
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-shared-downloader-kernel-cache
          ./push.xsh

  silverblue-shared-builder-brave:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-shared-builder-brave
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-shared-builder-brave
          ./push.xsh

  silverblue-shared-downloader-python-validity-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-shared-downloader-python-validity-cache
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-shared-downloader-python-validity-cache
          ./push.xsh

  almalinux-zfs-base:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd almalinux-zfs-base
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd almalinux-zfs-base
          ./push.xsh

  silverblue-zfs-base:
    needs: silverblue-shared-downloader-kernel-cache
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-zfs-base
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-zfs-base
          ./push.xsh

  silverblue-base:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-base
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-base
          ./push.xsh

  silverblue-shuttle-sz170r8v2:
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-shuttle-sz170r8v2
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-shuttle-sz170r8v2
          ./push.xsh

  silverblue-supermicro-x10drw-it:
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-supermicro-x10drw-it
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-supermicro-x10drw-it
          ./push.xsh

  silverblue-thinkpad-p1g1:
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-thinkpad-p1g1
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-thinkpad-p1g1
          ./push.xsh

  silverblue-thinkpad-p1g5:
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-thinkpad-p1g5
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-thinkpad-p1g5
          ./push.xsh

  silverblue-thinkpad-t470:
    needs: [silverblue-base, silverblue-shared-builder-brave, silverblue-shared-downloader-python-validity-cache]
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-thinkpad-t470
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-thinkpad-t470
          ./push.xsh

  silverblue-zbox-mi548:
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-zbox-mi548
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-zbox-mi548
          ./push.xsh

  silverblue-orico:
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-orico
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-orico
          ./push.xsh

  silverblue-ace-t8-pro:
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-ace-t8-pro
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-ace-t8-pro
          ./push.xsh

  silverblue-neosmay-xxx-ac8f-yyy:
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Build container image
        run: |
          pushd silverblue-neosmay-xxx-ac8f-yyy
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd silverblue-neosmay-xxx-ac8f-yyy
          ./push.xsh
