
name: Build
on:
  schedule:
    - cron: "00 10 * * *" # 6:00 AM EDT
  push:
    branches: ["main"]
  workflow_dispatch: # This line enables manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  silverblue-shared-downloader-kernel-cache:
    env:
      SRC_DIR: silverblue-shared-downloader-kernel-cache
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-shared-builder-brave:
    env:
      SRC_DIR: silverblue-shared-builder-brave
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-shared-downloader-python-validity-cache:
    env:
      SRC_DIR: silverblue-shared-downloader-python-validity-cache
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  almalinux-zfs-base:
    env:
      SRC_DIR: almalinux-zfs-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-zfs-base:
    env:
      SRC_DIR: silverblue-zfs-base
    needs: silverblue-shared-downloader-kernel-cache
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-base:
    env:
      SRC_DIR: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-shuttle-sz170r8v2:
    env:
      SRC_DIR: silverblue-shuttle-sz170r8v2
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-supermicro-x10drw-it:
    env:
      SRC_DIR: silverblue-supermicro-x10drw-it
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-thinkpad-p1g1:
    env:
      SRC_DIR: silverblue-thinkpad-p1g1
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-thinkpad-p1g5:
    env:
      SRC_DIR: silverblue-thinkpad-p1g5
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-thinkpad-t470:
    env:
      SRC_DIR: silverblue-thinkpad-t470
    needs: [silverblue-base, silverblue-shared-builder-brave, silverblue-shared-downloader-python-validity-cache]
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-zbox-mi548:
    env:
      SRC_DIR: silverblue-zbox-mi548
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-orico:
    env:
      SRC_DIR: silverblue-orico
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-ace-t8-pro:
    env:
      SRC_DIR: silverblue-ace-t8-pro
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  silverblue-neosmay-xxx-ac8f-yyy:
    env:
      SRC_DIR: silverblue-neosmay-xxx-ac8f-yyy
    needs: silverblue-base
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Free Disk Space (android, dotnet, boost, CodeQL)
        run: |
          sudo rm -rf /usr/local/lib/android # ~12 GB
          sudo rm -rf /usr/share/dotnet # ~2 GB
          sudo rm -rf /usr/local/share/boost # ~1 GB
          sudo rm -rf "$AGENT_TOOLSDIRECTORY/CodeQL" # ~5 GB

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh
